apiVersion: v1
kind: Namespace
metadata:
  name: foo5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: foo5
  labels:
    clusternet-app: multi-cluster-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
